parameters:
#    s2_gaming_terrain_generator.example.class: Teo\Symfony2Gaming\TerrainGeneratorBundle\Example

services:
#    s2_gaming_terrain_generator.example:
#        class: %s2_gaming_terrain_generator.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
